Remove stray space in definition (#134)
## What did we change?

Via #133, there was a stray whitespace in the config which caused:

```
Error: unrecognized cop or department Rails/ BulkChangeTable found in /usr/local/bundle/gems/ezcater_rubocop-7.1.1/conf/rubocop_rails.yml
Did you mean `Rails/BulkChangeTable`?
```